# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  storage:
    taskfile: ./storage/Taskfile.yml
    dir: ./storage
  native:
    taskfile: ./native/Taskfile.yml
    dir: ./native

tasks:
  tree:
    cmd: tree --gitignore

  build:
    cmds:
      - task native:build
      - task storage:build

  build:release:
    cmds:
      - task native:build:release
      - task storage:build:release

  run:
    cmds:
      - task native:build
      - task storage:run
