# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  coordinator:
    taskfile: ./coordinator/Taskfile.yml
    dir: ./coordinator
  storage:
    taskfile: ./storage/Taskfile.yml
    dir: ./storage
  native:
    taskfile: ./native/Taskfile.yml
    dir: ./native

tasks:
  proto:
    cmd: buf generate

  tree:
    cmd: tree --gitignore
