# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  configure:
    cmd: cmake --fresh -B build -G "Ninja Multi-Config" .
    env:
      CMAKE_EXPORT_COMPILE_COMMANDS: 1
      sources:
        - CMakeLists.txt

  build:
    deps: [configure]
    cmd: cmake --build build

  build:release:
    deps: [configure]
    cmd: cmake --build build --config Release
