# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  build:
    cmd: cargo build

  build:release:
    cmd: cargo build --release

  run:
    cmd: cargo run

  run:release:
    cmd: cargo run --release
